[package]
name = "roth-conversion-calc"
version = "0.1.0"
authors = ["David Orchard <if_coding@fastmail.com>"]
edition = "2018"

[dependencies]
pathfinding = "1.1.12"
failure = "0.1.5"
lazy_static = "1.3.0"
